title: FX Trading Hub
description: 初心者から上級者までのFX情報サイト
baseurl: ""           # もしサブディレクトリで公開しているなら書き換え
url: "https://your-username.github.io"
markdown: kramdown
theme: minima         # デフォルトテーマ。後で自作に置き換え可
plugins:
  - jekyll-feed
